#!/bin/bash
#
# Automate re-flashing an LPC17xx device running the USB bootloader from Linux.
#
# Example:
#    $ ./flash.sh /dev/sdc new-firmware.bin
#
if [ $# -ne 2 ]; then
    echo "Usage: lpcflash <device/name> <firmware>"
    echo "EX: lpcflash /dev/sdc firmware.bin"
    exit 1
fi
DEVICE=$1
FIRMWARE=$2

echo "Deleting existing firmware..."
sudo umount /media/NGX\ CRPDBLE/
sudo mdel -i $DEVICE ::/ngx_tech.bin
while [ $? != 0 ]; do
    sleep 2

    echo "Re-trying delete of existing firwmare..."
    sudo mdel -i $DEVICE ::/ngx_tech.bin
done

echo "Copying new firmware..."
sudo mcopy -i $DEVICE $FIRMWARE ::/firmware.bin
echo "Done."
